name: Tests

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  tests:
    strategy:
      matrix:
        os-version: [ubuntu-latest]
        node-version: [16.x]
    runs-on: ${{ matrix.os-version }}

    steps:
    - name: Clone Repo
      uses: actions/checkout@v3.0.2

    - name: Prepare java
      uses: actions/setup-java@v3.3.0
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install clojure cli
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: 1.11.1.1113

    - name: Test ${{ matrix.node-version }}
      uses: actions/setup-node@v3.2.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        echo "TODO implement it"
        # npm ci
        # npm run ci:tests
  # Deploy linode
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: executing remote ssh commands using password
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: 212.71.255.252
  #       username: root
  #       password: ${{ secrets.PASSWORD }}
  #       port: 22  
  #       script: |
  #             cd shortulr-deploy
  #             git pull
  #             docker-compose up -d --build app
